### ISSUE TITLE
Incompatible dictionary error

### ISSUE THREAD

**Issue by general-yatso** [chakki-works/Japanese-Company-Lexicon#16]
I’m trying to run mecab using jcl slim as a user dictionary in combination with unidic lite as system dictionary but keep getting incompatible dictionary error for jcl slim. I’m basically following instruction listed within the below link.

https://fintan.jp/?p=5325

I’m obviously a beginner and apologies in advance if I’m not providing enough information but please kindly advise if any other information would help to resolve the matter.

**Comment by BrambleXu** [comment]
Please try the usage on [wiki](https://github.com/chakki-works/Japanese-Company-Lexicon/wiki/JCLdic-Usage) page. Pay attention to the format you used.

**Comment by general-yatso** [comment]
Thank you for your response.  I tried the instruction on wiki but still getting the same error. Does it have anything to do with the encoding of 2 dictionaries?

**Comment by BrambleXu** [comment]
I tried the combination of ipadic and jcl slim, it works fine. But when trying unidic (I download it from [here](https://qiita.com/y-ken/items/ca3a6f7d7c79fdbe703e)), it failed. 

I use this [script](https://gist.github.com/Kimtaro/ab137870ad4a385b2d79)  to compile the csv format to mecab format. And the encoding is utf8. Because ipadic works fine with jcl slim, the encoding of ipaidc should be utf8 too.

The fast way to solve the problem is to convert the encoding of unidic to utf8. But I tried lots of methods and failed. Because we do not know the encoding of unidic in the first place. 

Here is my advise. Try your best to fine a way to convert unidic to utf8, or convert jcl slim to the encoding of unidic. Or you can just use other dictionaryies to replace unidic.

**Comment by general-yatso** [comment]
Thank you for your kind help. It helps just knowing I'm not the only one. I'll give it a try with ipadic and jcl.

**Comment by general-yatso** [comment]
It worked!!
